import:
 - gocodebox/lifterlms:.config/travis/add-on.yml

jobs:
  include:
  - name: "Test OpenAPI Spec"
    language: node_js
    node_js: lts/*
    before_install:
    install:
      - npm ci
    script:
      - npm run test
  - stage: deploy
    language: node_js
    node_js: lts/*
    if: branch = trunk AND env(GH_TOKEN) IS present
    before_install:
    install:
      - npm ci
    script: npm run build:docs && npm run gh-pages
